apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-boot-k8s
  template:
    metadata:
      labels:
        app: python-boot-k8s
    spec:
      containers:
      - name: python-boot-k8s
        image: python-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: python-k8ssvc
spec:
  selector:
    app: python-boot-k8s
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
