apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
  namespace: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: pramila188/python-app:latest
        ports:
        - containerPort: 80

