apiVersion: v1
kind: Service
metadata:
  name: my-python-app
  namespace: python
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007 # You can specify a port or let Kubernetes assign one
  selector:
    app: my-python-app

